[platformio]
src_dir = firmware/holes
default_envs = hole1_node

[common]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    fastled/FastLED@^3.10.3
    256dpi/MQTT@^2.5.2
lib_extra_dirs = firmware/shared/lib
build_flags = -Ifirmware/shared/config
monitor_speed = 115200

[env:hole1_node]
extends = common
build_src_filter = -<*> +<hole1_node/src/**>

[env:hole2_node]
extends = common
build_src_filter = -<*> +<hole2_node/src/**>

[env:hole3_node]
extends = common
build_src_filter = -<*> +<hole3_node/src/**>

[env:hole4_node]
extends = common
build_src_filter = -<*> +<hole4_node/src/**>
